services:
  db:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - "./data:/data"
  haste-server:
    build: "."
    depends_on:
      - db
    environment:
      - STORAGE_TYPE=redis
      - STORAGE_HOST=db
      - STORAGE_PORT=6379
      - STORAGE_DB=0
    ports:
      - "7777:7777"
    restart: unless-stopped
version: "3.0"
