name: Build & Push Docker Image to container image registry

on:
  release:
    types: [created]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "Dockerfile"

jobs:
  docker:
    uses: clytage/workflows/.github/workflows/docker-build.yml@main
    secrets: inherit
